version: '3.9'

services:
  portfolio-api:
    build:
      context: .
    env_file:
      - ${ENV_FILE_NAME}
    ports:
      - '${HOST_PORT}:${HOST_PORT}'
    networks:
      - portfolio-network
    depends_on:
      - postgres-db
    command: >
      bash -c "yarn migration:run && yarn start:${STAGE}"
  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - ${ENV_FILE_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - portfolio-network

volumes:
  postgres-data:

networks:
  portfolio-network:
    driver: bridge
