export const mockAdminService = () => ({
  getUser: jest.fn(),
  updateUser: jest.fn(),
  getEducations: jest.fn(),
  createEducation: jest.fn(),
  updateEducation: jest.fn(),
  deleteEducation: jest.fn(),
  getWorkExperiences: jest.fn(),
  createWorkExperience: jest.fn(),
  updateWorkExperience: jest.fn(),
  deleteWorkExperience: jest.fn(),
  // TODO - RETOCAR
  getProjects: jest.fn(),
  createProject: jest.fn(),
  updateProject: jest.fn(),
  deleteProject: jest.fn(),
  getSkills: jest.fn(),
  createSkill: jest.fn(),
  updateSkill: jest.fn(),
  deleteSkill: jest.fn(),
  getContact: jest.fn(),
  createContact: jest.fn(),
  updateContact: jest.fn(),
  deleteContact: jest.fn(),
  getBulletPoints: jest.fn(),
  createBulletPoint: jest.fn(),
  updateBulletPoint: jest.fn(),
  deleteBulletPoint: jest.fn(),
  getTags: jest.fn(),
  createTag: jest.fn(),
  updateTag: jest.fn(),
  deleteTag: jest.fn(),
  // TODO - RETOCAR
  getTechnologies: jest.fn(),
  createTechnology: jest.fn(),
  updateTechnology: jest.fn(),
  deleteTechnology: jest.fn(),
});
