name: Deploy to Vercel

on:
  push:
    branches:
      - main # Change this to your main branch name
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --prod

      - name: Run database migrations
        run: |
          npm run migrate  # Replace with your actual migration script/command
